---
- name: Install OnlyOffice
  hosts: localhost
  tasks:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install OnlyOffice
      community.general.flatpak:
        name: org.onlyoffice.desktopeditors
        state: present

- name: Get user
  hosts: localhost
  tasks:
    - name: Get the logged-in user
      ansible.builtin.shell:
        cmd: "who | grep '(:0)' | awk '{print $1}'"
      register: logged_in_user
      changed_when: false

- name: Install UI customizations
  hosts: localhost
  tasks:
    - name: Retrieve desktop theme
      ansible.builtin.git:
        repo: https://github.com/ZorinOS/zorin-desktop-themes.git
        dest: /root/themes
        update: no

    - name: Retrieve icons
      ansible.builtin.git:
        repo: https://github.com/yeyushengfan258/Win11-icon-theme.git
        dest: /root/icons
        update: no

    - name: Install icons
      ansible.builtin.shell: 
        cmd: ./install.sh -a
        chdir: /root/icons

    - name: Copy themes
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /usr/share/themes/
      loop: /root/themes/Zorin*

    - name: Set gnome icons
      ansible.builtin.command: 
        cmd: gsettings set org.gnome.desktop.interface icon-theme Win11-blue

    - name: Set gnome theme
      ansible.builtin.command:
        cmd: gsettings set org.gnome.desktop.interface gtk-theme ZorinBlue-Light

    - name: Send notification to the logged-in user
      ansible.builtin.command:
        cmd: notify-send "Ansible Playbook" "Your task is complete!"
      become_user: "{{ logged_in_user.stdout }}"
