---
- name: Install OnlyOffice
  hosts: localhost
  tasks:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo

    - name: Install OnlyOffice
      community.general.flatpak:
        name: org.onlyoffice.desktopeditors
        state: present

- name: Install UI customizations
  hosts: localhost
  tasks:
    - name: Retrieve desktop theme
      ansible.builtin.git:
        repo: https://github.com/ZorinOS/zorin-desktop-themes.git
        dest: /root/themes
        update: no

    - name: Retrieve icons
      ansible.builtin.git:
        repo: https://github.com/yeyushengfan258/Win11-icon-theme.git
        dest: /root/icons
        update: no

    - name: Install icons
      ansible.builtin.shell: 
        cmd: ./install.sh -a
        chdir: /root/icons
