---
- name: Install OnlyOffice
  hosts: localhost
  tasks:
    - name: Add the flathub flatpak repository remote to the user installation
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install OnlyOffice
      community.general.flatpak:
        name: org.onlyoffice.desktopeditors
        state: present
